CREATE TABLE IF NOT EXISTS `sys_dict` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `dict_code` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL COMMENT '字典编码',
  `dict_name` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL COMMENT '字典名称',
  `message_code` VARCHAR(32) DEFAULT NULL COMMENT '国际化编码',
  `dict_source` INT DEFAULT NULL COMMENT '来源:1-字典数据;2-动态SQL',
  `dict_sql` VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '动态sql',
  `sort_index` INT DEFAULT 0 COMMENT '排序',
  `remark` VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备注',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '租户ID',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT UNSIGNED DEFAULT '0' COMMENT '删除标志:0-正常;1-删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_dict_code` (`dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典';

CREATE TABLE IF NOT EXISTS `sys_dict_item` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `dict_id` BIGINT UNSIGNED NOT NULL COMMENT '字典ID',
  `dict_code` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL COMMENT '字典编码',
  `item_name` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL COMMENT '字典项名称',
  `item_value` VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COMMENT '字典项值',
  `sort_index` INT DEFAULT 0 COMMENT '排序',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '租户ID',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT UNSIGNED DEFAULT '0' COMMENT '删除标志:0-正常;1-删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_dict_item_id_code` (`dict_id`,`dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典项';
