CREATE TABLE IF NOT EXISTS sys_http_request_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    trace_id VARCHAR(64) COMMENT '追踪ID',
    app_name VARCHAR(64) COMMENT '应用名称',
    request_time DATETIME COMMENT '请求时间',
    response_time DATETIME COMMENT '响应时间',
    cost_time BIGINT COMMENT '耗时(毫秒)',
    request_method VARCHAR(16) COMMENT '请求方法',
    request_url VARCHAR(1024) COMMENT '请求URL',
    request_headers TEXT COMMENT '请求头',
    request_body LONGTEXT COMMENT '请求体',
    response_status INT COMMENT '响应状态码',
    response_headers TEXT COMMENT '响应头',
    response_body LONGTEXT COMMENT '响应体',
    client_ip VARCHAR(64) COMMENT '客户端IP',
    error_message TEXT COMMENT '错误信息',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_trace_id (trace_id),
    INDEX idx_request_time (request_time),
    INDEX idx_app_name (app_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HTTP请求日志表'; 